### ISSUE TITLE
Colors do not seem to work inside an element

### ISSUE THREAD

**Issue by ghost** [othree/jsdoc-syntax.vim#4]
Hi !

Colors do not seem to work when the comment concerns an element inside an element, such as a method in an object or a function in another function.

![screenshot](http://pix.toile-libre.org/upload/original/1563213686.png)

**Comment by dajoha** [comment]
Hello,

I have the same problem, for my part it seems that the syntax file from [vim-javascript](https://github.com/pangloss/vim-javascript) causes conflicts.

**Comment by othree** [comment]
Can you provide a simple code snippets?

**Comment by othree** [comment]
@yolenoyer vim-javascript have their native support https://github.com/pangloss/vim-javascript#configuration-variables

And I can't reproduce this using Vim's built in syntax based on the screenshot.

**Comment by dajoha** [comment]
@othree Oh, sorry, I really thought the vim-javascript variable `g:javascript_plugin_jsdoc` was 0 by default, so when I was testing, I just commented `let g:javascript_plugin_jsdoc = 1`.
But if I set this variable to 0 explicitly, jsdoc-syntax is working like a charm.
